registry:
  etcd:
    address: etcdaddress
database:
  host: 127.0.0.1
  port: 3306
  database: hpcmanager
  username: mysqlroot
  password: mysqlpass
redis:
  address: 172.17.0.4:6379
  password:
  db: 0
rabbitmq:
  address: 172.17.0.6:5672
